
importScripts('cn.js'); // imports the cn.js "glue" script generated by emscripten

// webassembly cryptonight is called here.
var hash = Module.cwrap('hash_cn', 'string', ['string', 'string', 'number'])

// A few helper (string) functions to help us working with the hex string
// which is used 

function zeroPad(num, places) {
	var zero = places - num.toString().length + 1;
	return Array(+(zero > 0 && zero)).join("0") + num;
}

// function hex2int(s) {
	// return parseInt(s.match(/[a-fA-F0-9]{2}/g).reverse().join(''), 16);
// }

function int2hex(i) {
	return (zeroPad(i.toString(16), 8)).match(/[a-fA-F0-9]{2}/g).reverse().join('');
}

// function getRandomInt(min, max) {
	// return Math.floor(Math.random() * (max - min + 1)) + min;
// }

var increm = 0;
var job_id = 0;
var job_done = false;
onmessage = function (e) {
	// console.log('onmessage', e);

	var jbthrt = e.data;
	var job = jbthrt.job;
	var thrt = jbthrt.throttle;

	var bsuccess = false;
	var res = "";
	var hexnonce = 0;
	// calculate a cryptonight hash
	var calcHash = function () {
		if (job !== null) {
			// job.blob = "0303f6d6ccd7056647ae7cd18be02c22cdcc36c0d97b2c741ed7d0d089c1129270cfbeefc8da420000000030a80070b84b85a3a20d24db230c5bebbee94f74bd7e06265df29ac99059c3aa0c";
			// job.target = "9bc42000";

			// var inonce = getRandomInt(0, 0xFFFFFFFF);
			if (job_id != job.job_id) {
				// console.log("increm went to ", increm);
				increm = jbthrt.w_start;
				job_done = false;
				job_id = job.job_id; // assign one time
			}
			try {
				// res = hash(job.blob, job.target, inonce);
				res = hash(job.blob, job.target, increm);
				if (increm == jbthrt.w_stop) {
					job_done = true;
				}
				// hexnonce = int2hex(inonce);
				hexnonce = int2hex(increm);
				bsuccess = (res != "");
				if (bsuccess) {
					// console.log('res', job.blob, job.target, inonce, bsuccess, res);
					// console.log('res', job.blob, job.target, increm, bsuccess, res);
				}
				increm++;
			}
			catch (err) {
				console.log(err);
			}
		}
	};

	// submit a cryptonight hash
	var submit = function () {
		if (bsuccess) {
			var msg = {
				type: "submit",
				params: {
					job_id: job.job_id,
					nonce: hexnonce,
					result: res
				}
			};
			postMessage(JSON.stringify(msg));
		} else if (job_done) {
			postMessage("kill");
		} else {
			postMessage("nothing");
		}
	};

	if (thrt === 0) {
		calcHash();
		submit();
	} 
	else 
	{
		// var t0 = performance.now();
		// calcHash();
		// var dt = performance.now() - t0;
		// var timePerHash = dt - t0;		
		// var throttleWait = 1 / (1 - thrt);
		
		// var sleept = Math.min(2e3, timePerHash * throttleWait);
		
		// setTimeout(submit, sleept);
		var t0 = performance.now();
		calcHash();
		var dt = performance.now() - t0;

		var sleept = Math.round(thrt / (100 - thrt + 10) * dt);
		setTimeout(submit, sleept);
	}
};